-- MySQL Script generated by MySQL Workbench
-- Tue Apr 26 11:12:41 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sidra_rank
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sidra_rank` ;

-- -----------------------------------------------------
-- Schema sidra_rank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sidra_rank` DEFAULT CHARACTER SET utf8 ;
USE `sidra_rank` ;

-- -----------------------------------------------------
-- Table `sidra_rank`.`1814_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sidra_rank`.`1814_users` ;

CREATE TABLE IF NOT EXISTS `sidra_rank`.`1814_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidra_rank`.`1814_sidras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sidra_rank`.`1814_sidras` ;

CREATE TABLE IF NOT EXISTS `sidra_rank`.`1814_sidras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `place` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidra_rank`.`1814_score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sidra_rank`.`1814_score` ;

CREATE TABLE IF NOT EXISTS `sidra_rank`.`1814_score` (
  `1814_id_sidra_fk` INT NOT NULL,
  `1814_id_user_fk` INT NOT NULL,
  `score` TINYINT(5) NULL,
  PRIMARY KEY (`1814_id_sidra_fk`, `1814_id_user_fk`),
  INDEX `fk_1814_sidras_has_1814_users_1814_users1_idx` (`1814_id_user_fk` ASC),
  INDEX `fk_1814_sidras_has_1814_users_1814_sidras_idx` (`1814_id_sidra_fk` ASC),
  CONSTRAINT `fk_1814_sidras_has_1814_users_1814_sidras`
    FOREIGN KEY (`1814_id_sidra_fk`)
    REFERENCES `sidra_rank`.`1814_sidras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_1814_sidras_has_1814_users_1814_users1`
    FOREIGN KEY (`1814_id_user_fk`)
    REFERENCES `sidra_rank`.`1814_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
